on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Install dependencies
      uses: php-actions/composer@v6
      with:
        php_version: "7.4"
        version: 1
        command: composer install

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: public_html/api.source/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/public/**
          fileToExclude.txt
